### Write a NumPy program to compute the determinant of a given square array.

[1 0]
[1 2]

In [ ]:
import numpy as np
a = [[1,0],[1,2]]
np.linalg.det(a)

2.0

### Write a NumPy program to compute the multiplication of two given matrixes.

In [ ]:
a = [[1,2],[3,4]]
b = [[5,6],[7,8]]
np.dot(a,b)

array([[19, 22],
       [43, 50]])

### Write a NumPy program to compute the eigenvalues and right eigenvectors of a given square array.

In [ ]:
w,v = np.linalg.eig(a)
print(f"Eigenvalues are: {w} and {v}")

Eigenvalues are: [-0.37228132  5.37228132] and [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


### Write a NumPy program to compute the inverse of a given matrix.

In [ ]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### Write a NumPy program to calculate the QR decomposition of a given matrix.

In [ ]:
np.linalg.qr(a)

QRResult(Q=array([[-0.31622777, -0.9486833 ],
       [-0.9486833 ,  0.31622777]]), R=array([[-3.16227766, -4.42718872],
       [ 0.        , -0.63245553]]))

### Write a NumPy program to compute the sum of the diagonal element of a given array.

In [ ]:
np.trace(a)

5

### Write a NumPy program to compute the outer product of two given vectors.

![image.png](attachment:image.png)

In [2]:
import numpy as np
p = np.array([[1,0],[0,1]])
q = np.array([[1,2],[3,4]])
np.outer(p,q)

array([[1, 2, 3, 4],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 2, 3, 4]])