### 1. Write a NumPy program to test whether none of the elements of a given array is zero.

In [13]:
import numpy as np
arr = [1,2,3,4,5]
np.all(arr)

True

### 2. Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [14]:
np.any(arr)

True

### 3. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given

In [15]:
import numpy as np
a = [1,2,3,4,5]
b = [1,2,3,4,5]
np.array_equal(a,b)

True

### 4. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [19]:
zeros = np.zeros(10)
ones = np.ones(10)
fives = np.ones(10)*5
comb = np.concatenate((zeros,ones,fives))
print(comb)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


### 5. Write a NumPy program to create an array of the integers from 30 to70.

In [20]:
np.arange(30,71)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

### 6. Write a NumPy program to create a 3x3 identity matrix

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 7. Write a NumPy program to generate a random number between 0 and 1

In [22]:
np.random.rand()

0.9711061185417719

### 8. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [23]:
np.random.randn(15)

array([-3.28172782e-01,  1.64134173e+00,  2.67212524e-01, -3.34059180e-01,
       -5.32371371e-01,  1.40636891e-03, -6.76041254e-01,  6.47806336e-01,
        4.87904378e-01,  3.72965479e-01,  1.97501865e+00, -5.83464445e-01,
       -1.10176026e+00, -1.13497960e+00, -2.95752518e-01])

### 9. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [25]:
a= np.arange(15,55)
print(a[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


### 10. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10

In [26]:
np.random.randint(0,10,15)

array([3, 0, 3, 2, 3, 5, 6, 4, 1, 4, 6, 2, 0, 7, 0])

### 11. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [29]:
a = np.ones((10,10))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 12. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2,3, 4, 5.

In [31]:
a = np.zeros((5,5))
a[np.arange(5),np.arange(5)] = [1,2,3,4,5]
print(a)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


### 13. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.


In [23]:

import numpy as np
a = np.ones((4,4))
a[np.arange(4),np.arange(4)] = [0,0,0,0]
#b = np.diag_indices_from(a)
#a[b] = 0
print(a)

[[0. 1. 1. 1.]
 [1. 0. 1. 1.]
 [1. 1. 0. 1.]
 [1. 1. 1. 0.]]


### 14. Write a NumPy program to save two given arrays into a single file in compressed format (.npz for

In [4]:
a = [1,2,3,4,4]
b = [1,2,3,4,5,6]
np.savez('arr',a,b)

### 15. Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values.

In [25]:
np.random.rand(40)

array([0.0176609 , 0.34565281, 0.00405659, 0.06687122, 0.10891456,
       0.62507687, 0.25644952, 0.9120199 , 0.05377777, 0.34987045,
       0.39425221, 0.9883513 , 0.666435  , 0.37724267, 0.89610741,
       0.99437817, 0.67244438, 0.68371455, 0.49290972, 0.50761371,
       0.17863262, 0.67945854, 0.7718057 , 0.29271816, 0.55032906,
       0.95283004, 0.48430926, 0.35156146, 0.03705967, 0.050785  ,
       0.01167338, 0.53940533, 0.43210212, 0.72913061, 0.5866037 ,
       0.05136366, 0.01183209, 0.83696934, 0.53864934, 0.96109567])

### 16. Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.

In [3]:
import numpy as np
a = np.random.randint(1,100,10)
inut = int(input("Enter a number: "))
b = a[(a>inut)]
print(a)
print(b)


Enter a number: 10
[ 7 30  2 25 67 44 35 70 57 86]
[30 25 67 44 35 70 57 86]
